In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
data = pd.read_csv('drugs.csv')
data.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [4]:
feature_cols = ['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']
x = data[feature_cols].values
y = data.Drug

In [5]:
from sklearn import preprocessing

cod_sex = preprocessing.LabelEncoder()
cod_sex.fit(['F', 'M'])
x[:,1] = cod_sex.transform(x[:,1])

cod_bp = preprocessing.LabelEncoder()
cod_bp.fit(['LOW', 'NORMAL', 'HIGH'])
x[:,2] = cod_bp.transform(x[:,2])

cod_cholesterol = preprocessing.LabelEncoder()
cod_cholesterol.fit(['NORMAL', 'HIGH'])
x[:,3] = cod_cholesterol.transform(x[:,3])

In [6]:
# Creacion de grupos de entrenamiento y de prueba 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Gini

In [29]:
# Crear objeto de clasificacion del arbol de decision
clf = DecisionTreeClassifier()

# Aplicacion del algoritmo de arboles de decision a los grupos de entrenamiento
clf = clf.fit(x_train, y_train)

# Prediccion de la respuesta para el grupo de prueba
y_pred = clf.predict(x_test)

In [30]:
# Matriz de confusion
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 7,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 26]])

In [31]:
# Estadisticas de desempeno
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         7
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         6
       drugX       1.00      1.00      1.00        18
       drugY       1.00      1.00      1.00        26

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60

In [35]:
from sklearn import tree
import graphviz
import pydotplus
from PIL import Image

In [37]:
# Creacion de infromacion para el arbol (reglas de decision)
dot_data = tree.export_graphviz(clf, out_file=None, feature_names=feature_cols, class_names=['Drug A', 'Drug B', 'Drug C', 'Drug X', 'Drug Y'])

# Creacion de la grafica del arbol
graph = pydotplus.graph_from_dot_data(dot_data)

In [38]:
# Creacion del arbol en formato PDF
graph.write_pdf('drugs_gini.pdf')

#Creacion del arbol em formato PNG
graph.write_png('drugs_gini.png')

image = Image.open('drugs_gini.png')
image.show()

# Entropy

In [19]:
# Crear objeto de clasificacion del arbol de decision
clf = DecisionTreeClassifier(criterion='entropy', max_depth=4)

# Aplicacion del algoritmo de arboles de decision a los grupos de entrenamiento
clf = clf.fit(x_train, y_train)

# Prediccion de la respuesta para el grupo de prueba
y_pred = clf.predict(x_test)

In [20]:
# Estadisticas de desempeno
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         7
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         6
       drugX       1.00      1.00      1.00        18
       drugY       1.00      1.00      1.00        26

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60

In [41]:
# Creacion de infromacion para el arbol (reglas de decision)
dot_data = tree.export_graphviz(clf, out_file=None, feature_names=feature_cols, class_names=['Drug A', 'Drug B', 'Drug C', 'Drug X', 'Drug Y'])

# Creacion de la grafica del arbol
graph = pydotplus.graph_from_dot_data(dot_data)

In [43]:
# Creacion del arbol en formato PDF
graph.write_pdf('drugs_entropy.pdf')

#Creacion del arbol em formato PNG
graph.write_png('drugs_entropy.png')

image = Image.open('drugs_entropy.png')
image.show()

# Pronostico paciente de prueba

In [45]:
x_pron = [50, 0, 0, 1, 15.302]
x_pron = pd.DataFrame(x_pron)
x_pron = x_pron.transpose()
x_pron

      0    1    2    3       4
0  50.0  0.0  0.0  1.0  15.302

In [46]:
# Crear objeto de clasificacion del arbol de decision
clf = DecisionTreeClassifier()

# Aplicacion del algoritmo de arboles de decision a los grupos de entrenamiento
clf = clf.fit(x_train, y_train)

# Prediccion de la respuesta para el grupo de prueba
y_pred = clf.predict(x_pron)
y_pred

array(['drugY'], dtype=object)